### ISSUE TITLE
Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by philsbury** [sindresorhus/compare-urls#5]
Hi @sindresorhus,

Have come across this error being thrown in Safari:

`Invalid regular expression: invalid group specifier name`

Which I think is coming from here:

`urlObj.pathname = urlObj.pathname.replace(/(?<!\b(?:[a-z][a-z\d+\-.]{1,50}:))\/{2,}/g, '/');`

Seems fine for me on a local environment (`.test` over https), but it doesn't like it on live environments.

A bit of a quick google suggests the negative look behind, but my regex isn't good enough to be sure!

Thanks
Phil

**Comment by sindresorhus** [comment]
Safari does indeed not support negative lookbehind. This package mainly targets Node.js though. For browser use, it's up to you to transpile to support certain browsers.
